safe: false
source: .
destination: ./_site
plugins_dir: ./_plugin
highlighter: rouge
markdown: kramdown
exclude: ['CNAME', 'Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md', '.sass-cache', '.asset-cache', '_site']

plugins:
  - jekyll-assets

title: "TCN-6270: Mobile And Wireless Networks"
description: Spring 2019 (Florida International University)
author: Alex Afanasyev

baseurl: "/~afanasyev/classes/spring19/TCN-6270"
url: "https://users.cs.fiu.edu"

timezone: America/New_York

# spreadsheets:
#   google_client_id: _data/google-id.json
#   spreadsheet:
#     - "14C356v5Lnojr1c7G62qAI438zeUce4AvPuMuEs-zptg"

assets:
  cache: .sass-cache

  sources:
    - _assets/css
    - _assets/images
    - _assets/fonts
    - _assets/js
    - _assets/bower

  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"
